#######################################################################################################################
### LOVELACE ###
#######################################################################################################################
mode: yaml
resources: !include /config/lovelace/lovelace_resources.yaml
dashboards: # name needs to contain a hyphen (-)
  # lovelace-tablet:
  #   mode: yaml
  #   filename: ui-lovelace-table.yaml
  #   title: Tablet
  #   icon: mdi:cellphone-android
  #   show_in_sidebar: true
  #   require_admin: false
  # lovelace-mobile:
  #   mode: yaml
  #   filename: ui-lovelace-mobile.yaml
  #   title: Mobile
  #   icon: mdi:tablet-android
  #   show_in_sidebar: true
  #   require_admin: false
  lovelace-test:
    mode: yaml
    filename: ui-lovelace-test.yaml
    title: Test
    icon: mdi:tools
    show_in_sidebar: true
    require_admin: true

