###############################################################################
## Lovelace Configuration
## dashboard name needs to contain a hyphen (-)
###############################################################################
mode: yaml
resources: !include /config/lovelace/lovelace_resources.yaml
dashboards:
  lovelace-kiosk:
    mode: yaml
    filename: ui-lovelace-kiosk.yaml
    title: 'Kiosk'
    icon: mdi:tablet-android
    show_in_sidebar: true
    require_admin: false
  lovelace-mobile:
    mode: yaml
    filename: ui-lovelace-mobile.yaml
    title: 'Mobile'
    icon: mdi:cellphone
    show_in_sidebar: true
    require_admin: false
  lovelace-system:
    mode: yaml
    filename: ui-lovelace-system.yaml
    title: 'System'
    icon: mdi:chart-areaspline
    show_in_sidebar: true
    require_admin: true
  lovelace-cast:
    mode: yaml
    filename: ui-lovelace-cast.yaml
    title: 'Cast'
    icon: mdi:cast
    show_in_sidebar: true
    require_admin: false
  lovelace-test:
    mode: yaml
    filename: ui-lovelace-test.yaml
    title: 'Test'
    icon: mdi:tools
    show_in_sidebar: true
    require_admin: true
