###############################################################################
## Alarm Clock Settings Entity
###############################################################################
type: custom:fold-entity-row
head:
  type: custom:template-entity-row
  entity: sensor.alarm_clock_next_alarm
  name: "Alarm Clock Settings"
  icon: mdi:cog
  state: ""
  tap_action:
    action: none
padding: 5
entities:
  - entity: switch.alarm_clock_snooze
  - entity: input_number.alarm_clock_snooze_time

  - entity: timer.alarm_clock_snooze
    card_mod:
      style: |
        :host {
          --paper-item-icon-color:
            {% if is_state('timer.alarm_clock_snooze','idle') %} var(--state-icon-color)
            {% else %} var(--state-icon-active-color)
            {% endif %}
            ;
        }

  - entity: input_boolean.alarm_clock_increase_volume
    tap_action:
      action: none

  - entity: input_number.alarm_clock_play_delay
    tap_action:
      action: none

  - entity: input_boolean.alarm_clock_failed
    card_mod:
      style: |
        :host {
          --paper-item-icon-active-color: var(--entity-critical-color);
        }

  - type: custom:auto-entities
    filter:
      template: "{{ states.alert|selectattr('attributes.category','eq','alarm_clock')|map(attribute='entity_id')|list }}"
    sort:
      method: name
      ignore_case: true
    card:
      type: custom:fold-entity-row
      padding: 5
      head:
        entity: input_boolean.alarm_clock_alerts
        card_mod:
          style: |
            :host {
              --paper-item-icon-color: var(--entity-warning-color);
              --paper-item-icon-active-color:
                {% if states.alert|selectattr('attributes.category','eq','alarm_clock')
                    |selectattr('state','ne','idle')|list|count > 0 %} var(--entity-severe-color)
                {% else %} var(--state-icon-active-color)
                {% endif %}
              ;
            }

  - type: custom:auto-entities
    filter:
      include:
        - entity_id: "automation.alarm_clock_*"
    sort:
      method: name
      ignore_case: true
    card:
      type: custom:fold-entity-row
      padding: 5
      head:
        entity: sensor.dummy
        name: "Alarm Clock Automations"
        icon: mdi:sync-alert
        state: ""
        tap_action:
          action: none
