#######################################################################################################################
## Button Templates
#######################################################################################################################
menu_button:
  size: 50px # icon
  aspect_ratio: 1/1
  show_state: false
  show_name: false
  show_label: false
  show_entity_picture: false
  styles:
    state:
      - font-size: 14px
      - font-weight: bold

presence_button:
  size: 70% # icon
  aspect_ratio: 1/1
  show_state: true
  show_name: false
  show_label: true
  show_entity_picture: true

occupancy_button:
  styles:
    card:
      - background-color: '#101010'
    icon:
      - color: '#B0B0B0'
    name:
      - color: '#B0B0B0'
    label:
      - font-size: 12px
      - font-weight: bold