type: entities
show_header_toggle: false
state_color: true
entities:
  - type: custom:auto-entities
    filter:
      include:
        - entity_id: "automation.jason_*"
    sort:
      method: name
      ignore_case: true
    card:
      type: custom:fold-entity-row
      head:
        entity: input_boolean.jason_medication_enabled
        state_color: true
      padding: 0

  - entity: input_boolean.jason_medication_active
  - entity: input_number.jason_medication_day_interval
  - entity: input_datetime.jason_medication_days
  - entity: input_datetime.jason_medication_afternoons
  - entity: input_datetime.jason_medication_weekends
card_mod:
  class: popup
