###############################################################################
## Check Home Assistant Configuration Update Entity
###############################################################################
type: conditional
conditions:
  - entity: binary_sensor.check_home_assistant_configuration_update_available
    state: 'on'
row:
  type: custom:multiple-entity-row
  entity: sensor.check_home_assistant_configuration_version
  name: 'Check Home Assistant Update'
  icon: mdi:database
  state_header: Current
  entities:
    - entity: sensor.check_home_assistant_configuration_newest_version
      name: 'Latest'
