###############################################################################
## Check Home Assistant Configuration Stats Entity
###############################################################################
type: conditional
conditions:
  - entity: binary_sensor.check_home_assistant_configuration_running
    state: "on"
row:
  type: custom:multiple-entity-row
  entity: sensor.check_home_assistant_configuration_cpu_percent
  name: "Check Home Assistant Configuration"
  icon: mdi:database
  state_header: "CPU"
  entities:
    - entity: sensor.check_home_assistant_configuration_memory_percent
      name: "MEM"
