###############################################################################
## Climate Settings Card
###############################################################################
type: entities
title: Climate Settings
icon: mdi:thermostat
show_header_toggle: false
state_color: true
entities:
  - entity: binary_sensor.nest_connected
    card_mod:
      style: |
        :host {
          --paper-item-icon-color: var(--entity-critical-color);
        }

  - entity: climate.thermostat

  - entity: input_boolean.climate_occupancy_control
    card_mod:
      style: |
        :host {
          --paper-item-icon-color: var(--entity-warning-color);
        }

  - entity: input_boolean.hvac_presence_override

  - type: custom:fold-entity-row
    head:
      entity: sensor.hvac_boost
    padding: 5
    entities:
      - entity: input_boolean.hvac_boost

  - type: custom:fold-entity-row
    head:
      type: custom:template-entity-row
      icon: mdi:thermometer
      name: Thermostat Temperatures
    padding: 5
    entities:
      - type: custom:numberbox-card
        entity: input_number.home_heat_temperature
        name: 'Home Heat Temp'
        unit: false
        step: 0.5
        icon_plus: mdi:plus-box-outline
        icon_minus: mdi:minus-box-outline

      - type: custom:numberbox-card
        entity: input_number.home_cool_temperature
        name: 'Home Cool Temp'
        unit: false
        step: 0.5
        icon_plus: mdi:plus-box-outline
        icon_minus: mdi:minus-box-outline

      - type: custom:numberbox-card
        entity: input_number.night_heat_temperature
        name: 'Night Heat Temp'
        unit: false
        step: 0.5
        icon_plus: mdi:plus-box-outline
        icon_minus: mdi:minus-box-outline

      - type: custom:numberbox-card
        entity: input_number.night_cool_temperature
        name: 'Night Cool Temp'
        unit: false
        step: 0.5
        icon_plus: mdi:plus-box-outline
        icon_minus: mdi:minus-box-outline

      - type: custom:numberbox-card
        entity: input_number.guest_heat_temperature
        name: 'Guest Heat Temp'
        unit: false
        step: 0.5
        icon_plus: mdi:plus-box-outline
        icon_minus: mdi:minus-box-outline

      - type: custom:numberbox-card
        entity: input_number.guest_cool_temperature
        name: 'Guest Cool Temp'
        unit: false
        step: 0.5
        icon_plus: mdi:plus-box-outline
        icon_minus: mdi:minus-box-outline

  - type: custom:fold-entity-row
    head:
      type: custom:template-entity-row
      icon: mdi:thermometer-alert
      name: Climate Alert Thresholds
    padding: 5
    entities:
      - type: custom:numberbox-card
        entity: input_number.low_temperature_threshold
        name: 'Low Temp Alert'
        unit: false
        step: 0.5
        icon_plus: mdi:plus-box-outline
        icon_minus: mdi:minus-box-outline

      - type: custom:numberbox-card
        entity: input_number.high_temperature_threshold
        name: 'High Temp Alert'
        unit: false
        step: 0.5
        icon_plus: mdi:plus-box-outline
        icon_minus: mdi:minus-box-outline

      - type: custom:numberbox-card
        entity: input_number.high_humidity_threshold
        name: 'Humidity Alert'
        unit: false
        icon_plus: mdi:plus-box-outline
        icon_minus: mdi:minus-box-outline

      - type: custom:numberbox-card
        entity: input_number.spa_low_temperature_threshold
        name: 'Spa Low Temp Alert'
        unit: false
        step: 0.5
        icon_plus: mdi:plus-box-outline
        icon_minus: mdi:minus-box-outline

  - type: custom:auto-entities
    filter:
      template: "{{ states.alert|selectattr('attributes.category','eq','climate')|map(attribute='entity_id')|list }}"
    sort:
      method: name
      ignore_case: true
    card:
      type: custom:fold-entity-row
      head:
        entity: input_boolean.climate_alerts
        state_color: true
        card_mod:
          style: |
            :host {
              --paper-item-icon-color: var(--entity-warning-color);
              --paper-item-icon-active-color:
                {% if states.alert|selectattr('attributes.category','eq','climate')
                    |selectattr('state','ne','idle')|list|count > 0 %} var(--entity-severe-color)
                {% else %} var(--state-icon-active-color)
                {% endif %}
              ;
            }
      padding: 5

  - type: custom:auto-entities
    filter:
      include:
        - entity_id: 'automation.climate_*'
    sort:
      method: name
      ignore_case: true
    card:
      type: custom:fold-entity-row
      head:
        entity: input_boolean.climate_automation
        state_color: true
        card_mod:
          style: |
            :host {
              --paper-item-icon-color: var(--entity-warning-color);
            }
      padding: 5

  - type: custom:auto-entities
    filter:
      template: "{{ states.alert|selectattr('attributes.category','eq','spa')|map(attribute='entity_id')|list }}"
    sort:
      method: name
      ignore_case: true
    card:
      type: custom:fold-entity-row
      head:
        entity: input_boolean.spa_alerts
        state_color: true
        card_mod:
          style: |
            :host {
              --paper-item-icon-color: var(--entity-warning-color);
              --paper-item-icon-active-color:
                {% if states.alert|selectattr('attributes.category','eq','spa')
                    |selectattr('state','ne','idle')|list|count > 0 %} var(--entity-severe-color)
                {% else %} var(--state-icon-active-color)
                {% endif %}
              ;
            }
      padding: 5

  - type: custom:auto-entities
    filter:
      include:
        - entity_id: 'automation.spa_*'
    sort:
      method: name
      ignore_case: true
    card:
      type: custom:fold-entity-row
      head:
        entity: input_boolean.spa_automation
        state_color: true
        card_mod:
          style: |
            :host {
              --paper-item-icon-color: var(--entity-warning-color);
            }
      padding: 5
card_mod:
  class: basic
