type: entities
entities:
  - entity: binary_sensor.spotify_connected
    card_mod:
      style: |
        :host {
          --paper-item-icon-color:
            {% if is_state('binary_sensor.spotify_connected','off') %} var(--entity-critical-color)
            {% else %} var(--state-icon-color)
            {% endif %}
          ;
        }

  - entity: binary_sensor.youtube_connected
    card_mod:
      style: |
        :host {
          --paper-item-icon-color:
            {% if is_state('binary_sensor.youtube_connected','off') %} var(--entity-critical-color)
            {% else %} var(--state-icon-color)
            {% endif %}
          ;
        }

  - !include /config/lovelace/include/entity/media/chromecast_devices.yaml

  - type: custom:fold-entity-row
    head:
      entity: input_boolean.mute_all
      card_mod:
        style: |
          :host {
            --paper-item-icon-color:
              {% if is_state('input_boolean.mute_all','on') %} var(--entity-warning-color)
              {% else %} var(--state-icon-color)
              {% endif %}
            ;
          }
      tap_action:
        action: fire-dom-event
        browser_mod:
          command: popup
          deviceID: this
          title: System Mute
          card: !include /config/lovelace/include/card/media/quiet_hours_settings.yaml
    padding: 5
    entities:
      - entity: input_number.timed_mute_duration
      - entity: timer.timed_mute_duration

  - type: custom:fold-entity-row
    head:
      entity: sensor.dummy
      name: Volume Settings
      icon: mdi:volume-medium
    padding: 5
    entities:
      - entity: input_number.media_default_volume
      - entity: input_number.volume_log_factor
      - entity: input_boolean.volume_balancing
      - entity: input_number.radio_volume_adjustment
      - entity: input_number.spotify_volume_adjustment
      - entity: input_number.youtube_volume_adjustment
      - type: custom:auto-entities
        filter:
          include:
            - entity_id: 'input_number.*_default_volume'
          exclude:
            - entity_id: input_number.media_default_volume
        sort:
          method: name
          ignore_case: true
        card:
          type: custom:fold-entity-row
          head:
            entity: sensor.dummy
            name: Default Volume Levels
            icon: mdi:volume-source
          padding: 5

  - type: custom:fold-entity-row
    head:
      entity: sensor.dummy
      name: Media Presets
      icon: mdi:animation-play
    padding: 5
    entities:
      - !include /config/lovelace/include/entity/media/media_preset/media_preset_enabled_wake.yaml
      - !include /config/lovelace/include/entity/media/media_preset/media_preset_enabled_morning.yaml
      - !include /config/lovelace/include/entity/media/media_preset/media_preset_enabled_sleep.yaml
      - !include /config/lovelace/include/entity/media/media_preset/media_preset_enabled_company.yaml
      - !include /config/lovelace/include/entity/media/media_preset/media_preset_enabled_shower.yaml
      - !include /config/lovelace/include/entity/media/media_preset/media_preset_enabled_jason.yaml
      - !include /config/lovelace/include/entity/media/media_preset/media_preset_enabled_sheri.yaml

  - type: custom:auto-entities
    filter:
      include:
        - entity_id: 'automation.media_player_*'
    sort:
      method: name
      ignore_case: true
    card:
      type: custom:fold-entity-row
      head:
        entity: input_boolean.media_player_automation
        card_mod:
          style: |
            :host {
              --paper-item-icon-color:
                {% if is_state('input_boolean.media_player_automation','off') %} var(--entity-warning-color)
                {% else %} var(--state-icon-color)
                {% endif %}
              ;
            }
      padding: 5

  - type: custom:fold-entity-row
    head:
      entity: sensor.dummy
      name: Media Booleans
    entities:
      - entity: input_boolean.resume_radio
      - entity: input_boolean.radio_failed
      - entity: input_boolean.resume_spotify
      - entity: input_boolean.spotify_failed
      - entity: input_boolean.resume_spotify_jason
      - entity: input_boolean.spotify_jason_failed
      - entity: input_boolean.resume_spotify_sheri
      - entity: input_boolean.spotify_sheri_failed
      - entity: input_boolean.resume_youtube
      - entity: input_boolean.youtube_failed
    padding: 5
card_mod:
  class: popup