type: entities
entities:
  - entity: input_boolean.startup_pending
  - entity: input_boolean.manual_mode
  - entity: input_boolean.supplemental_logging

  - type: custom:fold-entity-row
    head:
      entity: binary_sensor.low_battery_alert
      card_mod:
        style: |
          :host {
            --paper-item-icon-color:
              {% if is_state('binary_sensor.low_battery_alert','on') %} var(--entity-critical-color)
              {% else %} var(--state-icon-color)
              {% endif %}
              ;
          }
    entities:
      - entity: input_number.battery_alert_threshold

  - entity: input_select.log_level
  - entity: input_select.component_log_level

  - type: custom:auto-entities
    filter:
      template: "{{ states.alert|selectattr('attributes.category','eq','system')|map(attribute='entity_id')|list }}"
    sort:
      method: name
      ignore_case: true
    card:
      type: custom:fold-entity-row
      head:
        entity: input_boolean.system_alerts
        card_mod:
          style: |
            :host {
              --paper-item-icon-color:
                  {% if is_state('input_boolean.system_alerts','on') and states.alert|selectattr('attributes.category','eq','system')
                      |selectattr('state','ne','idle')|list|count > 0 %} var(--entity-critical-color)
                  {% elif is_state('input_boolean.system_alerts','off') %} var(--entity-warning-color)
                  {% else %} var(--state-icon-color)
                  {% endif %}
                ;
            }
        padding: 5

  - type: custom:auto-entities
    filter:
      include:
        - entity_id: "automation.system_*"
        - entity_id: "automation.hass_*"
    sort:
      method: name
      ignore_case: true
    card:
      type: custom:fold-entity-row
      head:
        entity: input_boolean.system_automation
        card_mod:
          style: |
            :host {
              --paper-item-icon-color:
                {% if is_state('input_boolean.system_automation','off') %} var(--entity-warning-color)
                {% else %} var(--state-icon-color)
                {% endif %}
              ;
            }
        padding: 5

  - type: custom:slider-entity-row
    entity: input_number.system_history_hours

  - type: button
    entity: script.internet_speedtest
    action_name: RUN TEST
    tap_action:
      action: call-service
      service: script.internet_speedtest

  - type: buttons
    entities:
      - entity: browser_mod.window_reload
        icon: mdi:file-refresh
        name: Refresh
        action_name: REFRESH
        tap_action:
          action: call-service
          confirmation:
            text: Are you sure you want to refresh your browser?
          service: browser_mod.window_reload

      - entity: homeassistant.restart
        icon: mdi:home-assistant
        name: Restart
        action_name: RESTART
        tap_action:
          action: call-service
          confirmation:
            text: Are you sure you want to restart Home Assistant?
          service: homeassistant.restart

      - entity: hassio.host_reboot
        icon: mdi:restore-alert
        name: Reboot
        action_name: REBOOT
        tap_action:
          action: call-service
          confirmation:
            text: Are you sure you want to reboot the server?
          service: hassio.host_reboot

card_mod:
  class: popup