type: entities
show_header_toggle: false
state_color: true
entities:
  - !include /config/lovelace/include/entity/house_alarm.yaml

  - entity: input_boolean.alarm_auto_arming
    style: |
      :host {
        --paper-item-icon-color: var(--entity-warning-color);
      }

  - entity: timer.alarm_pending
  - entity: timer.alarm_warning
  - entity: timer.alarm_triggered_reset

  - type: custom:slider-entity-row
    entity: input_number.alarm_history_hours
    full_row: false

  #AUTO - type: divider

  # - type: custom:auto-entities
  #   card:
  #     type: custom:fold-entity-row
  #     head:
  #       type: custom:template-entity-row
  #       icon: mdi:alert
  #       name: House Alarm Volumes
  #     padding: 0
  #   filter:
  #     include:
  #       - entity_id: "input_number.house_alarm*"
  #   sort:
  #     method: name
  #     ignore_case: true

  # - type: custom:auto-entities
  #   filter:
  #     template: "{{ states.alert|selectattr('attributes.category','eq','alarm')|map(attribute='entity_id')|list }}"
  #     options:
  #       state_color: true
  #   sort:
  #     method: name
  #     ignore_case: true
  #   card:
  #     type: custom:fold-entity-row
  #     padding: 0
  #     head:
  #       type: custom:template-entity-row
  #       icon: mdi:alert
  #       name: Alarm Alerts
  #       state_color: true
  #       style: |
  #         :host {
  #           --paper-item-icon-color:
  #               {% if states.alert|selectattr('attributes.category','eq','alarm')|selectattr('state','ne','idle')|list|count > 0 %} var(--entity-warning-color)
  #               {% else %} var(--state-icon-color)
  #               {% endif %}
  #             ;
  #         }

  # - type: custom:auto-entities
  #   filter:
  #     include:
  #       - entity_id: "automation.alarm_*"
  #         options:
  #           state_color: true
  #     exclude:
  #       - entity_id: "automation.alarm_clock*"
  #   sort:
  #     method: name
  #     ignore_case: true
  #   card:
  #     type: custom:fold-entity-row
  #     head:
  #       entity: input_boolean.alarm_automation
  #       state_color: true
  #     padding: 0
