type: entities
show_header_toggle: false
state_color: true
entities:
  - !include /config/lovelace/include/entity/alarm_clock_next_alarm_fold.yaml

  - entity: input_boolean.alarm_clock_auto_workdays
    tap_action:
      action: call-service
      service: browser_mod.popup
      service_data:
        title: Auto Alarm Clock
        deviceID: this
        large: false
        card: !include /config/lovelace/include/entities/alarm_clock_settings_auto.yaml
    double_tap_action:
      action: none
    hold_action:
      action: none

  - entity: input_boolean.alarm_clock_auto_weekends
    tap_action:
      action: call-service
      service: browser_mod.popup
      service_data:
        title: Auto Alarm Clock
        deviceID: this
        large: false
        card: !include /config/lovelace/include/entities/alarm_clock_settings_auto.yaml
    double_tap_action:
      action: none
    hold_action:
      action: none

  - entity: input_boolean.alarm_clock_guest
    tap_action:
      action: call-service
      service: browser_mod.popup
      service_data:
        title: Auto Alarm Clock
        deviceID: this
        large: false
        card: !include /config/lovelace/include/entities/alarm_clock_settings_auto.yaml
    double_tap_action:
      action: none
    hold_action:
      action: none

  - entity: input_boolean.alarm_clock_manual
    tap_action:
      action: call-service
      service: browser_mod.popup
      service_data:
        title: Manual Alarm Clock
        deviceID: this
        large: false
        card: !include /config/lovelace/include/entities/alarm_clock_settings_manual.yaml
    double_tap_action:
      action: none
    hold_action:
      action: none

  - type: divider

  - entity: input_boolean.alarm_clock_increase_volume
    tap_action:
      action: none
    double_tap_action:
      action: none
    hold_action:
      action: none

  - entity: input_boolean.alarm_clock_alerts
    tap_action:
      action: none
    double_tap_action:
      action: none
    hold_action:
      action: none

  - entity: input_number.alarm_clock_play_delay
    tap_action:
      action: none
    double_tap_action:
      action: none
    hold_action:
      action: none
    style: |
      :host {
        --paper-item-icon-color:
          {% if states('input_number.alarm_clock_play_delay')|int > 0 %} var(--state-icon-active-color)
          {% else %} var(--state-icon-color)
          {% endif %}
          ;
      }

  - type: divider

  - entity: input_boolean.alarm_clock_snooze

  - entity: input_number.alarm_clock_snooze_time
    style: |
      :host {
        --paper-item-icon-color:
          {% if states('input_number.alarm_clock_snooze_time')|int > 0 %} var(--state-icon-active-color)
          {% else %} var(--state-icon-color)
          {% endif %}
          ;
      }

  - entity: timer.alarm_clock_snooze
    style: |
      :host {
        --paper-item-icon-color:
          {% if is_state('timer.alarm_clock_snooze','idle') %} var(--state-icon-color)
          {% else %} var(--state-icon-active-color)
          {% endif %}
          ;
      }

  - type: divider

  - type: custom:auto-entities
    card:
      type: custom:fold-entity-row
      head:
        entity: sensor.dummy
        name: Alarm Clock Alerts
        icon: mdi:timer-outline
        tap_action:
          action: none
        double_tap_action:
          action: none
        hold_action:
          action: none
      padding: 0
    filter:
      include:
        - entity_id: "alert.alarm_clock_*"
    sort:
      method: name
      ignore_case: true

  - type: custom:auto-entities
    card:
      type: custom:fold-entity-row
      head:
        entity: sensor.dummy
        name: Alarm Clock Automation
        icon: mdi:timer-outline
        tap_action:
          action: none
        double_tap_action:
          action: none
        hold_action:
          action: none
      padding: 0
    filter:
      include:
        - entity_id: "automation.alarm_clock_*"
    sort:
      method: name
      ignore_case: true
