type: entities
show_header_toggle: false
entities:
  - entity: sensor.alarm_clock_nap #NOTE don't use entity include - recursive popup
    name: Next Nap Alarm
    tap_action:
      action: none
    double_tap_action:
      action: none
    hold_action:
      action: none
    style: |
      :host {
        --paper-item-icon-color:
          {% if is_state('sensor.alarm_clock_manual','Off') %} var(--state-icon-color)
          {% else %} var(--state-icon-active-color)
          {% endif %}
          ;
      }

  - type: divider

  - entity: input_select.alarm_clock_sound_nap
    style: |
      :host {
        --paper-item-icon-color:
          {% if is_state('sensor.alarm_clock_nap','Off') %} var(--state-icon-color)
          {% else %} var(--state-icon-active-color)
          {% endif %}
          ;
      }

  - type: conditional
    conditions:
      - entity: input_select.alarm_clock_sound_nap
        state: Radio
    row:
      entity: input_select.alarm_clock_radio_station_nap
    style: |
      :host {
        --paper-item-icon-color:
          {% if is_state('sensor.alarm_clock_nap','Off') %} var(--state-icon-color)
          {% else %} var(--state-icon-active-color)
          {% endif %}
          ;
      }

  - entity: input_select.alarm_clock_media_player_nap
    style: |
      :host {
        --paper-item-icon-color:
          {% if is_state('sensor.alarm_clock_nap','Off') %} var(--state-icon-color)
          {% else %} var(--state-icon-active-color)
          {% endif %}
          ;
      }

  - entity: input_number.alarm_clock_volume_nap
    style: |
      :host {
        --paper-item-icon-color:
          {% if is_state('sensor.alarm_clock_nap','Off') %} var(--state-icon-color)
          {% elif states('input_number.alarm_clock_volume_nap')|int > 0 %} var(--state-icon-active-color)
          {% else %} var(--entity-warning-color)
          {% endif %}
          ;
      }

  - entity: input_number.alarm_clock_nap_time
    style: |
      :host {
        --paper-item-icon-color:
          {% if is_state('sensor.alarm_clock_nap','Off') %} var(--state-icon-color)
          {% else %} var(--state-icon-active-color)
          {% endif %}
          ;
      }

  - entity: timer.alarm_clock_nap
    style: |
      :host {
        --paper-item-icon-color:
          {% if is_state('timer.alarm_clock_nap','idle') %} var(--state-icon-color)
          {% else %} var(--state-icon-active-color)
          {% endif %}
          ;
      }

  - type: divider

  - type: custom:paper-buttons-row
    buttons:
      - entity: input_boolean.alarm_clock_nap
        state_icons:
          'on': mdi:alarm-check
          'off': mdi:alarm-off
        state_text:
          'on': Alarm Set
          'off': Set Alarm
        state_styles:
          'on':
            button:
              color: var(--state-icon-active-color)
          'off':
            button:
              color: var(--state-icon-color)
        style:
          button:
            background-color: var(--table-row-alternative-background-color)
            border-radius: 40px
            padding: 10px
            font-size: 1.2rem
        tap_action:
          action: toggle
        double_tap_action:
          action: toggle
        hold_action:
          action: toggle

      - entity: input_boolean.alarm_clock_active_nap
        state_icons:
          'on': mdi:alarm-note
          'off': mdi:alarm-note-off
        state_text:
          'on': Stop Alarm
          'off': Test Play
        state_styles:
          'on':
            button:
              color: var(--state-icon-active-color)
          'off':
            button:
              color: var(--state-icon-color)
        style:
          button:
            background-color: var(--table-row-alternative-background-color)
            border-radius: 40px
            padding: 10px
            font-size: 1.2rem
        tap_action:
          action: call-service
          service: script.alarm_clock_stop
        double_tap_action:
          action: call-service
          service: script.alarm_clock_stop
        hold_action:
          action: call-service
          service: script.alarm_clock_play
          service_data:
            alarm_type: nap
            first_run: true
            test_play: true
