type: entities
show_header_toggle: false
entities:
  #AUTO - type: custom:auto-entities
  #   filter:
  #     include:
  #       - group: group.ceiling_fan_in_use_timers
  #   sort:
  #     method: name
  #     ignore_case: true
  #   card:
  #     type: custom:fold-entity-row
  #     head: binary_sensor.ceiling_fan_in_use
  #     padding: 0
  #     group_config:
  #       secondary_info: last-changed

  - entity: input_boolean.hvac_fan_control

  #AUTO - type: custom:auto-entities
  #   filter:
  #     include:
  #       - entity_id: "automation.ceiling_fan_*"
  #   sort:
  #     method: name
  #     ignore_case: true
  #   card:
  #     type: custom:fold-entity-row
  #     padding: 0
  #     head: input_boolean.ceiling_fan_automation