type: entities
title: Climate Settings
show_header_toggle: false
state_color: true
entities:
  - entity: binary_sensor.nest_connected
  - entity: binary_sensor.upstairs_thermostat_online
    name: Upstairs Thermostat

  - entity: automation.climate_occupancy_mode_control
    style: |
      :host {
        --paper-item-icon-color: var(--entity-warning-color);
      }

  - type: custom:fold-entity-row
    head:
      type: custom:template-entity-row
      icon: mdi:thermometer
      name: Thermostat Temperatures
    padding: 5
    entities:
      - entity: input_number.home_heat_temperature
        style: |
          :host {
            --paper-item-icon-color: var(--entity-heating-color);
          }

      - entity: input_number.home_cool_temperature
        style: |
          :host {
            --paper-item-icon-color: var(--entity-cooling-color);
          }

      - entity: input_number.night_heat_temperature
        style: |
          :host {
            --paper-item-icon-color: var(--entity-heating-color);
          }

      - entity: input_number.night_cool_temperature
        style: |
          :host {
            --paper-item-icon-color: var(--entity-cooling-color);
          }

      - entity: input_number.guest_heat_temperature
        style: |
          :host {
            --paper-item-icon-color: var(--entity-heating-color);
          }

      - entity: input_number.guest_cool_temperature
        style: |
          :host {
            --paper-item-icon-color: var(--entity-cooling-color);
          }

  - type: custom:fold-entity-row
    head:
      type: custom:template-entity-row
      icon: mdi:thermometer-lines
      name: Climate Alert Thresholds
      padding: 5
    entities:
      - entity: input_number.low_temperature_threshold
        style: |
          :host {
            --paper-item-icon-color: var(--entity-low-temp-color);
          }

      - entity: input_number.high_temperature_threshold
        style: |
          :host {
            --paper-item-icon-color: var(--entity-high-temp-color);
          }

      - entity: input_number.high_humidity_threshold
        style: |
          :host {
            --paper-item-icon-color: var(--entity-high-humidity-color);
          }
          
      - entity: input_number.spa_low_temperature_threshold
        style: |
          :host {
            --paper-item-icon-color: var(--entity-low-temp-color);
              }          

  - type: custom:slider-entity-row
    entity: input_number.climate_history_hours
    full_row: false

  - type: custom:template-entity-row
    icon: mdi:cog
    name: Ceiling Fan Settings
    tap_action:
      action: call-service
      service: browser_mod.popup
      service_data:
        deviceID: this
        title: Ceiling Fan Settings
        large: false
        card: !include /config/lovelace/include/entities/ceiling_fan_settings.yaml

  - type: custom:template-entity-row
    icon: mdi:cog
    name: Vent Fan Settings
    tap_action:
      action: call-service
      service: browser_mod.popup
      service_data:
        deviceID: this
        title: Vent Fan Settings
        large: false
        card: !include /config/lovelace/include/entities/vent_fan_settings.yaml

  #AUTO - type: custom:auto-entities
  #   filter:
  #     template: "{{ states.alert|selectattr('attributes.category','eq','climate')|map(attribute='entity_id')|list }}"
  #     options:
  #       state_color: true
  #   sort:
  #     method: name
  #     ignore_case: true
  #   card:
  #     type: custom:fold-entity-row
  #     padding: 0
  #     head:
  #       type: custom:template-entity-row
  #       icon: mdi:alert
  #       name: Climate Alerts
  #       state_color: true
  #       style: |
  #         :host {
  #           --paper-item-icon-color:
  #               {% if states.alert|selectattr('attributes.category','eq','climate')|selectattr('state','ne','idle')|list|count > 0 %} var(--entity-warning-color)
  #               {% else %} var(--state-icon-color)
  #               {% endif %}
  #             ;
  #         }

  # - type: custom:auto-entities
  #   card:
  #     type: custom:fold-entity-row
  #     head:
  #       entity: input_boolean.climate_automation
  #       state_color: true
  #     padding: 5
  #   filter:
  #     include:
  #       - entity_id: "automation.climate_*"
  #         options:
  #           state_color: true
  #   sort:
  #     method: name
  #     ignore_case: true

