type: entities
show_header_toggle: false
state_color: true
entities:
  - entity: binary_sensor.myq_connected
    style: |
      :host {
        --paper-item-icon-color: var(--entity-critical-color);
      }

  - entity: cover.garage_door_opener

  - type: custom:slider-entity-row
    entity: input_number.garage_history_hours
    full_row: false

  #DISABLED - entity: zwave.garage_thermostat
  - entity: input_number.garage_freeze_temperature
    name: Freeze Temp
    style: |
      :host {
        --paper-item-icon-color: var(--entity-low-temp-color);
      }

  - entity: input_number.garage_heat_temperature
    name: Heat Temp
    style: |
      :host {
        --paper-item-icon-color: var(--entity-high-temp-color);
      }

  #AUTO - type: custom:auto-entities
  #   filter:
  #     template: "{{ states.alert|selectattr('attributes.category','in',['garage','garage_climate'])|map(attribute='entity_id')|list }}"
  #     options:
  #       state_color: true
  #   sort:
  #     method: name
  #     ignore_case: true
  #   card:
  #     type: custom:fold-entity-row
  #     padding: 0
  #     head:
  #       type: custom:template-entity-row
  #       icon: mdi:alert
  #       name: Garage Alerts
  #       state_color: true
  #       style: |
  #         :host {
  #           --paper-item-icon-color:
  #               {% if states.alert|selectattr('attributes.category','in',['garage','garage_climate'])|selectattr('state','ne','idle')|list|count > 0 %} var(--entity-warning-color)
  #               {% else %} var(--state-icon-color)
  #               {% endif %}
  #             ;
  #         }

  # - type: custom:auto-entities
  #   card:
  #     type: custom:fold-entity-row
  #     head:
  #       entity: input_boolean.garage_door_automation
  #       state_color: true
  #     padding: 0
  #   filter:
  #     include:
  #       - entity_id: "automation.garage_*"
  #         options:
  #           state_color: true
  #     exclude:
  #       - entity_id: "automation.garage_climate*"
  #   sort:
  #     method: name
  #     ignore_case: true

  # - type: custom:auto-entities
  #   card:
  #     type: custom:fold-entity-row
  #     head:
  #       entity: input_boolean.garage_climate_automation
  #       state_color: true
  #     padding: 0
  #   filter:
  #     include:
  #       - entity_id: "automation.garage_climate_*"
  #         options:
  #           state_color: true
  #   sort:
  #     method: name
  #     ignore_case: true
