type: entities
show_header_toggle: false
state_color: true
entities:
  - entity: input_select.occupancy_mode
  - entity: input_boolean.occupancy_notifications
  - entity: input_boolean.occupancy_announcements

  - type: custom:slider-entity-row
    entity: input_number.presence_history_hours
    full_row: false

  #AUTO - type: custom:auto-entities
  #   filter:
  #     template: "{{ states.alert|selectattr('attributes.category','eq','presence')|map(attribute='entity_id')|list }}"
  #     options:
  #       state_color: true
  #   sort:
  #     method: name
  #     ignore_case: true
  #   card:
  #     type: custom:fold-entity-row
  #     padding: 0
  #     head:
  #       type: custom:template-entity-row
  #       icon: mdi:alert
  #       name: Presence Alerts
  #       state_color: true
  #       style: |
  #         :host {
  #           --paper-item-icon-color:
  #               {% if states.alert|selectattr('attributes.category','eq','presence')|selectattr('state','ne','idle')|list|count > 0 %} var(--entity-warning-color)
  #               {% else %} var(--state-icon-color)
  #               {% endif %}
  #             ;
  #         }

  # - type: custom:auto-entities
  #   filter:
  #     include:
  #       - entity_id: "automation.presence_*"
  #         options:
  #           state_color: true
  #   sort:
  #     method: name
  #     ignore_case: true
  #   card:
  #     type: custom:fold-entity-row
  #     head:
  #       entity: input_boolean.presence_automation
  #       state_color: true
  #   padding: 0
  #   entities:
