type: entities
show_header_toggle: false
entities:
  - entity: input_select.radio_station_shower
    name: Station
  - entity: input_select.radio_media_player_shower
    name: Speaker
  - entity: input_number.radio_volume_shower
    name: Volume

  - type: divider

  - type: custom:paper-buttons-row
    buttons:
      - entity: input_boolean.radio_enabled_shower
        state_icons:
          'on': mdi:alarm-check
          'off': mdi:alarm-off
        state_text:
          'on': Enabled
          'off': Disabled
        state_styles:
          'on':
            button:
              color: var(--paper-item-icon-active-color)
          'off':
            button:
              color: var(--paper-item-icon-color)
        style:
          button:
            background-color: var(--table-row-alternative-background-color)
            border-radius: 40px
            padding: 10px
            font-size: 1.2rem
        tap_action:
          action: toggle
        double_tap_action:
          action: toggle
        hold_action:
          action: toggle

      - entity: input_boolean.radio_on
        state_icons:
          'on': mdi:radio
          'off': mdi:radio
        state_text:
          'on': Play Radio
          'off': Play Radio
        state_styles:
          'on':
            button:
              color: var(--paper-item-icon-active-color)
          'off':
            button:
              color: var(--paper-item-icon-color)
        style:
          button:
            background-color: var(--table-row-alternative-background-color)
            border-radius: 40px
            padding: 10px
            font-size: 1.2rem
        tap_action:
          action: call-service
          service: browser_mod.toast
          service_data:
            message: "Hold to play radio preset. Double Tap to turn off radio."
            duration: 30000
        double_tap_action:
          action: call-service
          service: script.radio_off
        hold_action:
          action: call-service
          service: script.radio_play
          service_data:
            preset: Shower