type: entities
show_header_toggle: false
state_color: true
entities:
  - entity: input_select.media_preset_type_morning
    name: Media Type

  - type: conditional
    conditions:
      - entity: input_select.media_preset_type_morning
        state: Radio
    row:
      entity: input_select.media_preset_radio_morning
      name: Station

  - type: conditional
    conditions:
      - entity: input_select.media_preset_type_morning
        state: Spotify
    row:
      entity: input_select.media_preset_spotify_morning
      name: Playlist

  - entity: input_select.media_preset_speaker_morning
  - entity: input_number.media_preset_volume_morning

  - type: divider

  - type: custom:paper-buttons-row
    buttons:
      - entity: input_boolean.media_preset_enabled_morning
        state_icons:
          'on': mdi:alarm-check
          'off': mdi:alarm-off
        state_text:
          'on': Enabled
          'off': Disabled
        state_styles:
          'on':
            button:
              color: var(--state-icon-active-color)
          'off':
            button:
              color: var(--state-icon-color)
        style:
          button:
            background-color: var(--table-row-alternative-background-color)
            border-radius: 40px
            padding: 10px
            font-size: 1.2rem
        tap_action:
          action: toggle

      - entity: input_boolean.media_preset_morning
        state_icons:
          'on': mdi:radio
          'off': mdi:radio
        state_text:
          'on': Play Radio
          'off': Play Radio
        state_styles:
          'on':
            button:
              color: var(--state-icon-active-color)
          'off':
            button:
              color: var(--state-icon-color)
        style:
          button:
            background-color: var(--table-row-alternative-background-color)
            border-radius: 40px
            padding: 10px
            font-size: 1.2rem
        tap_action:
          action: call-service
          service: script.media_preset_play
          service_data:
            preset: morning
        double_tap_action:
          action: call-service
          service: script.media_preset_stop
          service_data:
            preset: morning
        hold_action:
          action: call-service
          service: script.media_preset_stop
          service_data:
            preset: morning