type: entities
show_header_toggle: false
state_color: true
entities:
  - entity: binary_sensor.google_traffic_connected
    style: |
      :host {
        --paper-item-icon-color: var(--entity-critical-color)
      }

  - entity: input_boolean.commute_alerts
    style: |
      :host {
        --paper-item-icon-color: var(--entity-warning-color);
      }

  - entity: input_number.commute_warning_threshold
    name: Warning Threshold
    style: |
      :host {
        --paper-item-icon-color: var(--state-icon-active-color);
      }

  - entity: input_number.commute_predeparture
    name: Commute Predeparture
    style: |
      :host {
        --paper-item-icon-color: var(--state-icon-active-color);
      }

  - type: call-service
    name: Update Traffic Sensors
    service: script.update_traffic_sensors
    action_name: UPDATE
    style: |
      :host {
        --paper-item-icon-color: var(--state-icon-active-color);
      }

  - type: section
    label: Days Commute Times
  - entity: input_datetime.days_leave_home_time
  - entity: input_datetime.days_arrive_work_time
  - entity: input_datetime.days_leave_work_time
  - entity: input_datetime.days_arrive_home_time

  - type: section
    label: Afternoons Commute Times
  - entity: input_datetime.afternoons_leave_home_time
  - entity: input_datetime.afternoons_arrive_work_time
  - entity: input_datetime.afternoons_leave_work_time
  - entity: input_datetime.afternoons_arrive_home_time

  - type: custom:auto-entities
    filter:
      include:
        - entity_id: "alert.traffic_*"
    sort:
      method: name
      ignore_case: true
    card:
      type: custom:fold-entity-row
      head:
        type: custom:dummy-entity-row
        entity: sensor.dummy
        icon: mdi:alert
        name: Traffic Alerts
      padding: 0

  - type: custom:auto-entities
    card:
      type: custom:fold-entity-row
      head:
        entity: sensor.dummy
        name: Traffic Automation
        icon: mdi:car-multiple
      padding: 0
    filter:
      include:
        - entity_id: "automation.traffic_*"
    sort:
      method: name
      ignore_case: true