type: entities
show_header_toggle: false
state_color: true
entities:
  - type: custom:fold-entity-row
    head: binary_sensor.upstairs_bathroom_humidity_fan
    padding: 0
    entities:
      - entity: sensor.upstairs_bathroom_humidity
      - entity: input_number.bathroom_humidity_fan_threshold
        name: Humidity Alert

  - type: custom:fold-entity-row
    head: binary_sensor.upstairs_bathroom_mold_fan
    padding: 0
    entities:
      - entity: sensor.upstairs_bathroom_mold_indicator
      - entity: input_number.mold_risk_threshold
        name: Mold Alert

  - type: custom:fold-entity-row
    head: binary_sensor.upstairs_bathroom_temperature_fan
    padding: 0
    entities:
      - entity: sensor.upstairs_bathroom_temperature
      - entity: input_number.bathroom_temperature_differential
        name: Temperature Alert

  - type: custom:fold-entity-row
    head: binary_sensor.vent_fan_in_use
    padding: 0
    group_config:
      secondary_info: last-changed
    entities: !include /config/include/entities/vent_fan_timer_entities.yaml

  - type: custom:auto-entities
    filter:
      include:
        - entity_id: "automation.vent_fan_*"
    sort:
      method: name
      ignore_case: true
    card:
      type: custom:fold-entity-row
      head: input_boolean.vent_fan_automation
      padding: 0
