type: entities
show_header_toggle: false
entities:
  - entity: binary_sensor.dark_sky_connected
  - entity: binary_sensor.noaa_connected
  - entity: input_boolean.display_weather_alerts
  - entity: input_boolean.display_gdacs_alerts
  - entity: input_boolean.morning_weather_enabled

  - type: custom:fold-entity-row
    head:
      type: custom:dummy-entity-row
      entity: sensor.dummy
      icon: mdi:thermometer-lines
      name: Temp Alert Thresholds
    padding: 0
    entities:
      - entity: input_number.outdoor_low_temperature_threshold
      - entity: input_number.outdoor_high_temperature_threshold

  - entity: input_number.weather_history_hours

  - type: custom:slider-entity-row
    entity: input_number.weather_history_hours
    full_row: true

  #AUTO - type: custom:auto-entities
  #   filter:
  #     template: "{{ states.alert|selectattr('attributes.category','eq','weather')|map(attribute='entity_id')|list }}"
  #   sort:
  #     method: name
  #     ignore_case: true
  #   card:
  #     type: custom:fold-entity-row
  #     padding: 0
  #     head:
  #       type: custom:template-entity-row
  #       icon: mdi:alert
  #       name: Weather Alerts
  #       state_color: true
  #       style: |
  #         :host {
  #           --paper-item-icon-color:
  #               {% if states.alert|selectattr('attributes.category','eq','weather')|selectattr('state','ne','idle')|list|count > 0 %} var(--entity-warning-color)
  #               {% else %} var(--state-icon-color)
  #               {% endif %}
  #             ;
  #         }

  # - type: custom:auto-entities
  #   filter:
  #     include:
  #       - entity_id: "automation.weather_*"
  #   sort:
  #     method: name
  #     ignore_case: true
  #   card:
  #     type: custom:fold-entity-row
  #     head: input_boolean.weather_automation
  #     padding: 0
