type: entities
show_header_toggle: false
state_color: true
entities:
  - type: custom:template-entity-row # must be template else recursive lovelace popup
    entity: sensor.next_bedtime
    state: "{{ state_attr('sensor.next_bedtime','12hour') }}"
    tap_action:
      action: none
    card_mod:
      style: |
        :host {
          --paper-item-icon-color:
            {% if is_state_attr('sensor.next_bedtime','12hour','OFF') %} var(--entity-warning-color)
            {% else %} var(--state-icon-active-color)
            {% endif %}
            ;
          }

  - entity: sensor.bedtime_today
    format: datetime

  - type: divider

  - type: custom:fold-entity-row
    head:
      entity: input_boolean.workday_night
      state_color: true
      tap_action:
        action: fire-dom-event
        browser_mod:
          command: popup
          deviceID: this
          title: Bed Times
          card: !include /config/lovelace/card/schedule/bedtime_picker.yaml
    padding: 0
    entities:
      - entity: input_datetime.days_bedtime
        card_mod:
          style: |
            :host {
              --paper-item-icon-color:
                {%- if is_state('input_boolean.workday_night','on') %} var(--state-icon-active-color)
                {% else %} var(--state-icon-color)
                {%- endif -%}
                ;
            }
      - entity: input_datetime.afternoons_bedtime
        card_mod:
          style: |
            :host {
              --paper-item-icon-color:
                {%- if is_state('input_boolean.workday_night','on') %} var(--state-icon-active-color)
                {% else %} var(--state-icon-color)
                {%- endif -%}
                ;
              }

  - type: custom:fold-entity-row
    head:
      entity: input_boolean.weekend_night
      state_color: true
      tap_action:
        action: fire-dom-event
        browser_mod:
          command: popup
          deviceID: this
          title: Bed Times
          card: !include /config/lovelace/card/schedule/bedtime_picker.yaml
    padding: 0
    entities:
      - entity: input_datetime.weekend_bedtime
        card_mod:
          style: |
            :host {
              --paper-item-icon-color:
                {%- if is_state('input_boolean.weekend_night','on') %} var(--state-icon-active-color)
                {% else %} var(--state-icon-color)
                {%- endif -%}
                ;
            }

  - type: custom:fold-entity-row
    head:
      entity: input_boolean.guest_night
      state_color: true
      tap_action:
        action: fire-dom-event
        browser_mod:
          command: popup
          deviceID: this
          title: Bed Times
          card: !include /config/lovelace/card/schedule/bedtime_picker.yaml
    padding: 0
    entities:
      - entity: input_datetime.guest_bedtime
        card_mod:
          style: |
            :host {
              --paper-item-icon-color:
                {%- if is_state('input_boolean.guest_night','on') %} var(--state-icon-active-color)
                {% else %} var(--state-icon-color)
                {%- endif -%}
                ;
            }

  - type: divider

  - entity: input_number.bedtime_delay
    card_mod:
      style: |
        :host {
          --paper-item-icon-color:
            {%- if states('input_number.bedtime_delay')|int(0) > 0 %} var(--state-icon-active-color)
            {% else %} var(--state-icon-color)
            {%- endif -%}
            ;
        }

  - entity: input_number.stay_awake_delay
    card_mod:
      style: |
        :host {
          --paper-item-icon-color:
            {%- if states('input_number.stay_awake_delay')|int(0) > 0 %} var(--state-icon-active-color)
            {% else %} var(--state-icon-color)
            {%- endif -%}
            ;
        }

  - entity: input_number.night_mode_delay
    card_mod:
      style: |
        :host {
          --paper-item-icon-color:
            {%- if states('input_number.night_mode_delay')|int(0) > 0 %} var(--state-icon-active-color)
            {% else %} var(--state-icon-color)
            {%- endif -%}
            ;
        }

  - entity: input_boolean.bedtime_delayed

  - type: conditional
    conditions:
      - entity: timer.bedtime_delay
        state_not: idle
    row:
      entity: timer.bedtime_delay

  - type: divider

  - !include /config/lovelace/card/media/include/media_preset_enabled_sleep.yaml

  - type: divider

  - type: custom:paper-buttons-row
    buttons:
      - entity: script.bedtime
        state_icons:
          'on': mdi:weather-sunset-up
          'off': mdi:weather-sunset-up
        state_text:
          'on': Bedtime Routine Running
          'off': Run Bedtime Routine
        state_styles:
          'on':
            button:
              color: var(--state-icon-active-color)
          'off':
            button:
              color: var(--primary-text-color)
        style:
          button:
            background-color: var(--table-row-alternative-background-color)
            border-radius: 40px
            padding: 10px
            font-size: 1.2rem
        tap_action:
          action: call-service
          service: script.bedtime
        double_tap_action:
          action: call-service
          service: script.turn_off
          service_data:
            entity_id: script.bedtime
        hold_action:
          action: call-service
          service: script.bedtime
card_mod:
  class: popup
