###############################################################################
## Bedtime Settings
###############################################################################
type: entities
show_header_toggle: false
state_color: true
entities:
  - type: attribute
    entity: sensor.bedtime_today
    attribute: '12hour'

  - type: attribute
    entity: sensor.next_bedtime
    attribute: '12hour'
    card_mod:
      style: |
        :host {
          --paper-item-icon-color:
            {% if is_state_attr('sensor.next_bedtime','12hour','OFF') %} var(--entity-warning-color)
            {% else %} var(--state-icon-active-color)
            {% endif %}
            ;
          }

  - type: custom:fold-entity-row
    head:
      entity: input_boolean.workday_night
      state_color: true
      tap_action:
        action: fire-dom-event
        browser_mod:
          command: popup
          deviceID: this
          hide_header: true
          title: 'Bed Times'
          card: !include /config/lovelace/card/schedule/bedtime_picker.yaml
    padding: 0
    entities:
      - entity: input_datetime.days_bedtime
        card_mod:
          style: |
            :host {
              --paper-item-icon-color:
                {%- if is_state('input_boolean.workday_night','on') %} var(--state-icon-active-color)
                {% else %} var(--state-icon-color)
                {%- endif -%}
                ;
            }
      - entity: input_datetime.afternoons_bedtime
        card_mod:
          style: |
            :host {
              --paper-item-icon-color:
                {%- if is_state('input_boolean.workday_night','on') %} var(--state-icon-active-color)
                {% else %} var(--state-icon-color)
                {%- endif -%}
                ;
              }

  - type: custom:fold-entity-row
    head:
      entity: input_boolean.weekend_night
      state_color: true
      tap_action:
        action: fire-dom-event
        browser_mod:
          command: popup
          deviceID: this
          hide_header: true
          title: 'Bed Times'
          card: !include /config/lovelace/card/schedule/bedtime_picker.yaml
    padding: 0
    entities:
      - entity: input_datetime.weekend_bedtime
        card_mod:
          style: |
            :host {
              --paper-item-icon-color:
                {%- if is_state('input_boolean.weekend_night','on') %} var(--state-icon-active-color)
                {% else %} var(--state-icon-color)
                {%- endif -%}
                ;
            }

  - type: custom:fold-entity-row
    head:
      entity: input_boolean.guest_night
      state_color: true
      tap_action:
        action: fire-dom-event
        browser_mod:
          command: popup
          deviceID: this
          hide_header: true
          title: 'Bed Times'
          card: !include /config/lovelace/card/schedule/bedtime_picker.yaml
    padding: 0
    entities:
      - entity: input_datetime.guest_bedtime
        card_mod:
          style: |
            :host {
              --paper-item-icon-color:
                {%- if is_state('input_boolean.guest_night','on') %} var(--state-icon-active-color)
                {% else %} var(--state-icon-color)
                {%- endif -%}
                ;
            }

  - type: divider

  - entity: input_number.bedtime_warning_delay
    card_mod:
      style: |
        :host {
          --paper-item-icon-color:
            {%- if states('input_number.bedtime_warning_delay')|int(0) > 0 %} var(--state-icon-active-color)
            {% else %} var(--state-icon-color)
            {%- endif -%}
            ;
        }

  - entity: input_number.bedtime_delay
    card_mod:
      style: |
        :host {
          --paper-item-icon-color:
            {%- if states('input_number.bedtime_delay')|int(0) > 0 %} var(--state-icon-active-color)
            {% else %} var(--state-icon-color)
            {%- endif -%}
            ;
        }

  - entity: input_number.night_mode_delay
    card_mod:
      style: |
        :host {
          --paper-item-icon-color:
            {%- if states('input_number.night_mode_delay')|int(0) > 0 %} var(--state-icon-active-color)
            {% else %} var(--state-icon-color)
            {%- endif -%}
            ;
        }

  - entity: input_boolean.bedtime_delayed

  - type: conditional
    conditions:
      - entity: timer.bedtime_delay
        state_not: idle
    row:
      entity: timer.bedtime_delay

  - entity: input_boolean.media_preset_enabled_sleep

  - type: divider

  - type: buttons
    entities:
      - entity: script.bedtime
        name: 'Run Bedtime'
        tap_action:
          action: call-service
          service: script.bedtime
        double_tap_action:
          action: call-service
          service: script.turn_off
          service_data:
            entity_id: script.bedtime
        hold_action:
          action: call-service
          service: script.toggle
          service_data:
            entity_id: script.bedtime
    card_mod:
      style:
        hui-buttons-base $: |
          .ha-scrollbar {
            justify-content: center;
          }
card_mod:
  class: popup
