type: entities
entities:
  - entity: binary_sensor.myq_connected
    card_mod:
      style: |
        :host {
          --paper-item-icon-color:
            {% if is_state('binary_sensor.myq_connected','off') %} var(--entity-critical-color)
            {% else %} var(--state-icon-color)
            {% endif %}
          ;
        }

  - entity: cover.garage_door_opener
    state_color: true

  - entity: input_boolean.garage_door_announcements
    card_mod:
      style: |
        :host {
          --paper-item-icon-color:
            {% if is_state('input_boolean.garage_door_announcements','off') %} var(--entity-warning-color)
            {% else %} var(--state-icon-color)
            {% endif %}
          ;
        }

  - entity: input_boolean.garage_door_alerts
    card_mod:
      style: |
        :host {
          --paper-item-icon-color:
            {% if is_state('input_boolean.garage_door_alerts','off') %} var(--entity-warning-color)
            {% else %} var(--state-icon-color)
            {% endif %}
          ;
        }

  - entity: input_boolean.garage_door_close_alert
    card_mod:
      style: |
        :host {
          --paper-item-icon-color:
            {% if is_state('input_boolean.garage_door_close_alert','on') %} var(--entity-warning-color)
            {% else %} var(--state-icon-color)
            {% endif %}
          ;
        }

  - entity: input_boolean.garage_door_open_alert
    card_mod:
      style: |
        :host {
          --paper-item-icon-color:
            {% if is_state('input_boolean.garage_door_open_alert','on') %} var(--entity-warning-color)
            {% else %} var(--state-icon-color)
            {% endif %}
          ;
        }

  - type: custom:fold-entity-row
    head:
      entity: sensor.dummy
      name: Garage Climate Settings
      icon: mdi:thermostat-box
    entities:
      - entity: input_number.garage_freeze_temperature
        name: Freeze Temp

      - entity: input_number.garage_heat_temperature
        name: Heat Temp

      - type: custom:auto-entities
        filter:
          template: "{{ states.alert|selectattr('attributes.category','eq','garage_climate')|map(attribute='entity_id')|list }}"
        sort:
          method: name
          ignore_case: true
        card:
          type: custom:fold-entity-row
          head:
            entity: input_boolean.garage_climate_alerts
            card_mod:
              style: |
                :host {
                  --paper-item-icon-color:
                      {% if is_state('input_boolean.garage_climate_alerts','on') and states.alert|selectattr('attributes.category','eq','garage_climate')
                          |selectattr('state','ne','idle')|list|count > 0 %} var(--entity-critical-color)
                      {% elif is_state('input_boolean.garage_climate_alerts','off') %} var(--entity-warning-color)
                      {% else %} var(--state-icon-color)
                      {% endif %}
                    ;
                }
          padding: 5

      - type: custom:auto-entities
        filter:
          include:
            - entity_id: "automation.garage_climate_*"
        sort:
          method: name
          ignore_case: true
        card:
          type: custom:fold-entity-row
          head:
            entity: input_boolean.garage_climate_automation
            card_mod:
              style: |
                :host {
                  --paper-item-icon-color:
                    {% if is_state('input_boolean.garage_climate_automation','off') %} var(--entity-warning-color)
                    {% else %} var(--state-icon-color)
                    {% endif %}
                  ;
                }
          padding: 5

  - type: custom:auto-entities
    filter:
      include:
        - entity_id: "automation.garage_*"
      exclude:
        - entity_id: "automation.garage_climate*"
    sort:
      method: name
      ignore_case: true
    card:
      type: custom:fold-entity-row
      head:
        entity: input_boolean.garage_door_automation
        card_mod:
          style: |
            :host {
              --paper-item-icon-color:
                {% if is_state('input_boolean.garage_door_automation','off') %} var(--entity-warning-color)
                {% else %} var(--state-icon-color)
                {% endif %}
              ;
            }
      padding: 5
card_mod:
  class: popup