###############################################################################
## Chill Scene Media Setting Entities
###############################################################################
- entity: select.media_preset_chill
  name: "Playlist"

- entity: select.media_preset_speaker_chill
  name: "Speaker"

- entity: input_number.media_preset_volume_chill
  name: "Volume"

- entity: input_boolean.media_preset_enabled_chill
  name: "Auto Play"

- entity: input_boolean.shuffle_chill
  name: "Shuffle Playlist"

- entity: input_boolean.repeat_chill
  name: "Repeat Playlist"

- entity: input_boolean.radio_chill
  name: "Radio Mode"

- type: button
  icon: mdi:multimedia
  name: "Chill Media"
  service: script.media_play
  action_name: "PLAY"
  tap_action:
    action: call-service
    service: script.media_play
    data:
      preset: chill
