###############################################################################
## Company Scene Media Setting Entities
###############################################################################
- entity: select.media_preset_company
  name: "Playlist"

- entity: select.media_preset_speaker_company
  name: "Speaker"

- entity: input_number.media_preset_volume_company
  name: "Volume"

- entity: input_boolean.media_preset_enabled_company
  name: "Auto Play"

- entity: input_boolean.shuffle_company
  name: "Shuffle Playlist"

- entity: input_boolean.repeat_company
  name: "Repeat Playlist"

- entity: input_boolean.radio_company
  name: "Radio Mode"

- type: button
  icon: mdi:multimedia
  name: "Company Media"
  service: script.media_play
  action_name: "PLAY"
  tap_action:
    action: call-service
    service: script.media_play
    data:
      preset: company
