###############################################################################
## Dexter Medication Settings
###############################################################################
type: entities
show_header_toggle: false
state_color: true
entities:
  - type: custom:auto-entities
    filter:
      include:
        - entity_id: "automation.*dexter_medication*"
    sort:
      method: name
      ignore_case: true
    card:
      type: custom:fold-entity-row
      padding: 0
      head:
        entity: input_boolean.dexter_medication_enabled
        name: "Reminder Enabled"

  - entity: input_boolean.dexter_medication_active
    name: "Reminder Active"

  - entity: input_number.dexter_medication_day_interval
    name: "Day Interval"

  - entity: input_number.dexter_medication_reminder_interval
    name: "Reminder Interval"

  - entity: input_datetime.dexter_medication_days
    name: "Days"

  - entity: input_datetime.dexter_medication_afternoons
    name: "Afternoons"

  - entity: input_datetime.dexter_medication_weekends
    name: "Weekends"
card_mod:
  class: basic
