###############################################################################
## Water Plants Reminder Settings
###############################################################################
type: entities
title: "Water Plants"
icon: mdi:sprout
show_header_toggle: false
state_color: true
entities:
  - type: custom:fold-entity-row
    padding: 0
    head:
      entity: binary_sensor.water_plants_reminder
      name: "Water Plants"
    entities:
      - entity: input_boolean.water_plants_enabled
        name: "Reminder Enabled"

      - entity: input_boolean.water_plants_active
        name: "Reminder Active"

  - entity: button.water_plants_done
    name: "Reminder Done"

  - type: custom:fold-entity-row
    padding: 0
    head:
      entity: input_number.water_plants_day_interval
      name: "Day Interval"
    entities:
      - entity: input_datetime.water_plants_days
        name: "Days"

      - entity: input_datetime.water_plants_afternoons
        name: "Afternoons"

      - entity: input_datetime.water_plants_weekends
        name: "Weekends"

  - entity: input_number.water_plants_notification_interval
    name: "Notification Interval"
card_mod:
  class: basic
