###############################################################################
## Disabled Automations
###############################################################################
type: custom:auto-entities
card:
  type: entities
  show_header_toggle: false
filter:
  include:
    - group: group.automation_controls
  exclude:
    - state: 'on'
card_mod:
  class: popup
