name: false
icon: false
info: true
power: true
source: true
sound_mode: true
controls: true
prev: true
next: true
play_pause: true
play_stop: true
volume: true
volume_level: true
mute: true
progress: true
runtime: true
artwork_border: true
power_state: true
icon_state: true
shuffle: true
state_label: true
