name: false # default false
icon: false # default false
info: true # default false
power: false # default false
source: true # default false
sound_mode: true # default true
controls: true # default false
prev: true # default false
next: true # default false
play_pause: true # default false
play_stop: true # default false
volume: false # default false
volume_level: false # default true
mute: true # default false
progress: true # default false
runtime: true # default true
artwork_border: true # default true
power_state: true # default true
icon_state: true # default true
shuffle: true # default true
state_label: true # default false
