name: false # default false
icon: false # default false
info: false # default false
power: false # default false
source: false # default false
sound_mode: false # default true
controls: false # default false
prev: false # default false
next: false # default false
play_pause: false # default false
play_stop: false # default false
volume: false # default false
volume_level: true # default true
mute: false # default false
progress: false # default false
runtime: false # default true
artwork_border: false # default true
power_state: false # default true
icon_state: false # default true
shuffle: false # default true
state_label: false # default false
