name: false
icon: false
info: false
power: true
source: false
sound_mode: true
controls: false
prev: true
next: true
play_pause: true
play_stop: false
volume: false
volume_level: false
mute: false
progress: false
runtime: false
artwork_border: false
power_state: false
icon_state: false
shuffle: true
state_label: false
