###############################################################################
## Bedroom Hub Settings - MASS
###############################################################################
type: entities
title: Bedroom Hub
show_header_toggle: false
entities:
  - entity: media_player.bedroom_hub
  - entity: media_player.mass_bedroom_hub
  - entity: number.bedroom_hub_announcements_volume_increase_relative
    name: Announcements Volume increase (relative)
  - entity: select.bedroom_hub_contenttype_to_stream_to_the_player
    name: Contenttype to stream to the player
  - entity: number.bedroom_hub_crossfade_duration
    name: Crossfade duration
  - entity: select.bedroom_hub_crossfade_mode
    name: Crossfade mode
  - entity: select.bedroom_hub_maximum_sample_rate_to_send_to_the_player
    name: Maximum sample rate to send to the player.
  - entity: select.bedroom_hub_repeat_mode
    name: Repeat mode
  - entity: switch.bedroom_hub_shuffle_enabled
    name: Shuffle enabled
  - entity: switch.bedroom_hub_volume_normalization_enabled
    name: Volume normalization enabled
  - entity: number.bedroom_hub_volume_normalization_target
    name: Volume normalization target
