###############################################################################
## Garage Speaker Settings - MASS
###############################################################################
type: entities
title: Garage Speaker
show_header_toggle: false
entities:
  - entity: media_player.garage_speaker
  - entity: media_player.mass_garage_speaker
  - entity: number.garage_speaker_announcements_volume_increase_relative
    name: Announcements Volume increase (relative)
  - entity: select.garage_speaker_contenttype_to_stream_to_the_player
    name: Contenttype to stream to the player
  - entity: number.garage_speaker_crossfade_duration
    name: Crossfade duration
  - entity: select.garage_speaker_crossfade_mode
    name: Crossfade mode
  - entity: select.garage_speaker_maximum_sample_rate_to_send_to_the_player
    name: Maximum sample rate to send to the player.
  - entity: select.garage_speaker_repeat_mode
    name: Repeat mode
  - entity: switch.garage_speaker_shuffle_enabled
    name: Shuffle enabled
  - entity: switch.garage_speaker_volume_normalization_enabled
    name: Volume normalization enabled
  - entity: number.garage_speaker_volume_normalization_target
    name: Volume normalization target
