###############################################################################
## Inside Speakers Settings - MASS
###############################################################################
type: entities
title: Inside Speakers
show_header_toggle: false
entities:
  - entity: media_player.inside_speakers
  - entity: media_player.mass_inside_speakers
  - entity: number.inside_speakers_announcements_volume_increase_relative
    name: Announcements Volume increase (relative)
  - entity: select.inside_speakers_contenttype_to_stream_to_the_player
    name: Contenttype to stream to the player
  - entity: number.inside_speakers_crossfade_duration
    name: Crossfade duration
  - entity: select.inside_speakers_crossfade_mode
    name: Crossfade mode
  - entity: select.inside_speakers_maximum_sample_rate_to_send_to_the_player
    name: Maximum sample rate to send to the player.
  - entity: select.inside_speakers_repeat_mode
    name: Repeat mode
  - entity: switch.inside_speakers_shuffle_enabled
    name: Shuffle enabled
  - entity: switch.inside_speakers_volume_normalization_enabled
    name: Volume normalization enabled
  - entity: number.inside_speakers_volume_normalization_target
    name: Volume normalization target
