###############################################################################
## Night Speakers Settings - MASS
###############################################################################
type: entities
title: Night Speakers
show_header_toggle: false
entities:
  - entity: media_player.night_speakers
  - entity: media_player.mass_night_speakers
  - entity: number.night_speakers_announcements_volume_increase_relative
    name: Announcements Volume increase (relative)
  - entity: select.night_speakers_contenttype_to_stream_to_the_player
    name: Contenttype to stream to the player
  - entity: number.night_speakers_crossfade_duration
    name: Crossfade duration
  - entity: select.night_speakers_crossfade_mode
    name: Crossfade mode
  - entity: select.night_speakers_maximum_sample_rate_to_send_to_the_player
    name: Maximum sample rate to send to the player.
  - entity: select.night_speakers_repeat_mode
    name: Repeat mode
  - entity: switch.night_speakers_shuffle_enabled
    name: Shuffle enabled
  - entity: switch.night_speakers_volume_normalization_enabled
    name: Volume normalization enabled
  - entity: number.night_speakers_volume_normalization_target
    name: Volume normalization target
