###############################################################################
## Scene Settings Card
###############################################################################
type: entities
title: Scene Settings
icon: mdi:movie-filter
show_header_toggle: false
state_color: true
entities:
  - type: custom:fold-entity-row
    head:
      type: section
      label: 'Chill Scene'
    entities:
      - type: custom:numberbox-card
        entity: input_number.chill_scene_duration
        name: Scene Duration
        icon: mdi:timer
        unit: time
        icon_plus: mdi:plus-box-outline
        icon_minus: mdi:minus-box-outline

      - entity: timer.chill_scene

      - type: custom:fold-entity-row
        head:
          type: custom:template-entity-row
          entity: sensor.rgb_chill_scene
          name: 'Chill Scene Light Color'
          state: ' '
          card_mod:
            style: |
              :host {
                --paper-item-icon-color: {{ states('sensor.rgb_chill_scene') }};
              }
        entities:
          - entity: input_number.rgb_red_chill
          - entity: input_number.rgb_green_chill
          - entity: input_number.rgb_blue_chill

      - entity: input_boolean.media_preset_enabled_chill
        tap_action:
          action: fire-dom-event
          browser_mod:
            command: popup
            deviceID: this
            title: 'Chill Media Preset'
            hide_header: true
            card: !include /config/lovelace/card/media/media_preset/media_preset_chill.yaml

  - type: custom:fold-entity-row
    head:
      type: section
      label: 'Company Scene'
    entities:
      - type: custom:numberbox-card
        entity: input_number.company_scene_duration
        unit: time
        icon_plus: mdi:plus-box-outline
        icon_minus: mdi:minus-box-outline

      - entity: timer.company_scene

      - type: custom:fold-entity-row
        head:
          type: custom:template-entity-row
          entity: sensor.rgb_company_scene
          name: 'Company Scene Light Color'
          state: ' '
          card_mod:
            style: |
              :host {
                --paper-item-icon-color: {{ states('sensor.rgb_company_scene') }};
              }
        entities:
          - entity: input_number.rgb_red_company
          - entity: input_number.rgb_green_company
          - entity: input_number.rgb_blue_company

      - entity: input_boolean.media_preset_enabled_company
        tap_action:
          action: fire-dom-event
          browser_mod:
            command: popup
            deviceID: this
            title: 'Company Media Preset'
            hide_header: true
            card: !include /config/lovelace/card/media/media_preset/media_preset_company.yaml

  - type: custom:fold-entity-row
    head:
      type: section
      label: Movie Scene'
    entities:
      - type: custom:numberbox-card
        entity: input_number.movie_scene_duration
        unit: time
        icon_plus: mdi:plus-box-outline
        icon_minus: mdi:minus-box-outline

      - entity: timer.movie_scene

  - type: custom:fold-entity-row
    head:
      type: section
      label: 'Shower Scene'
    entities:
      - type: custom:numberbox-card
        entity: input_number.shower_scene_duration
        unit: time
        icon_plus: mdi:plus-box-outline
        icon_minus: mdi:minus-box-outline

      - entity: timer.shower_scene

      - entity: input_boolean.media_preset_enabled_shower
        tap_action:
          action: fire-dom-event
          browser_mod:
            command: popup
            deviceID: this
            title: 'Shower Media Preset'
            hide_header: true
            card: !include /config/lovelace/card/media/media_preset/media_preset_shower.yaml
card_mod:
  class: basic
