###############################################################################
## Jason Medication Settings
###############################################################################
type: entities
show_header_toggle: false
state_color: true
entities:
  - type: custom:auto-entities
    filter:
      include:
        - entity_id: 'automation.*jason_medication*'
    sort:
      method: name
      ignore_case: true
    card:
      type: custom:fold-entity-row
      head:
        entity: input_boolean.jason_medication_enabled
        name: 'Reminder Enabled'
        state_color: true
      padding: 0

  - entity: input_boolean.jason_medication_active
    name: 'Reminder Active'

  - entity: input_number.jason_medication_day_interval
    name: 'Day Interval'

  - entity: input_datetime.jason_medication_days
    name: 'Days'

  - entity: input_datetime.jason_medication_afternoons
    name: 'Afternoons'

  - entity: input_datetime.jason_medication_weekends
    name: 'Weekends'
card_mod:
  class: popup
