###############################################################################
## Maddie Mealtime Settings
###############################################################################
type: entities
title: "Maddie Mealtime"
icon: mdi:dog
show_header_toggle: false
state_color: true
entities:
  - type: custom:auto-entities
    filter:
      include:
        - entity_id: "automation.*maddie_mealtime*"
    sort:
      method: name
      ignore_case: true
    card:
      type: custom:fold-entity-row
      head:
        entity: input_boolean.maddie_mealtime_enabled
        name: "Reminder Enabled"
        state_color: true
      padding: 0

  - entity: input_boolean.maddie_mealtime_active
    name: "Reminder Active"

  - entity: input_number.maddie_mealtime_reminder_interval
    name: "Reminder Interval"

  - entity: input_datetime.maddie_mealtime_days_1
    name: "Days 1"

  - entity: input_datetime.maddie_mealtime_days_2
    name: "Days 2"

  - entity: input_datetime.maddie_mealtime_days_3
    name: "Days 3"

  - entity: input_datetime.maddie_mealtime_afternoons_1
    name: "Afternoons 1"

  - entity: input_datetime.maddie_mealtime_afternoons_2
    name: "Afternoons 2"

  - entity: input_datetime.maddie_mealtime_afternoons_3
    name: "Afternoons 3"

  - entity: input_datetime.maddie_mealtime_weekends_1
    name: "Weekends 1"

  - entity: input_datetime.maddie_mealtime_weekends_2
    name: "Weekends 2"

  - entity: input_datetime.maddie_mealtime_weekends_3
    name: "Weekends 3"
card_mod:
  class: popup
