###############################################################################
## Maddie Mealtime Settings
###############################################################################
type: entities
show_header_toggle: false
state_color: true
entities:
  - type: custom:auto-entities
    filter:
      include:
        - entity_id: 'automation.*maddie_mealtime*'
    sort:
      method: name
      ignore_case: true
    card:
      type: custom:fold-entity-row
      head:
        entity: input_boolean.maddie_mealtime_enabled
        state_color: true
      padding: 0

  - entity: input_boolean.maddie_mealtime_active
  - entity: input_datetime.maddie_mealtime_days_1
  - entity: input_datetime.maddie_mealtime_days_2
  - entity: input_datetime.maddie_mealtime_days_3
  - entity: input_datetime.maddie_mealtime_afternoons_1
  - entity: input_datetime.maddie_mealtime_afternoons_2
  - entity: input_datetime.maddie_mealtime_afternoons_3
  - entity: input_datetime.maddie_mealtime_weekends_1
  - entity: input_datetime.maddie_mealtime_weekends_2
  - entity: input_datetime.maddie_mealtime_weekends_3
card_mod:
  class: popup
