###############################################################################
## UI Configuration
## dashboard name must contain a hyphen (-)
###############################################################################
mode: yaml
resources: !include /config/ui/resources.yaml
dashboards:
  ui-system:
    mode: yaml
    filename: ui-system.yaml
    title: "System"
    icon: mdi:chart-areaspline
    show_in_sidebar: true
    require_admin: true
  ui-kiosk:
    mode: yaml
    filename: ui-kiosk.yaml
    title: "Kiosk"
    icon: mdi:tablet
    show_in_sidebar: true
    require_admin: false
  ui-weather:
    mode: yaml
    filename: ui-weather.yaml
    title: "Weather"
    icon: mdi:weather-partly-snowy-rainy
    show_in_sidebar: true
    require_admin: false
  ui-cast:
    mode: yaml
    filename: ui-cast.yaml
    title: "Cast"
    icon: mdi:cast
    show_in_sidebar: true
    require_admin: false
  ui-test:
    mode: yaml
    filename: ui-test.yaml
    title: "Test"
    icon: mdi:tools
    show_in_sidebar: true
    require_admin: true
