###############################################################################
## UI Configuration
## dashboard name must contain a hyphen (-)
###############################################################################
mode: yaml
resources: !include /config/ui/resources.yaml
dashboards:
  ui-kiosk:
    mode: yaml
    filename: ui-kiosk.yaml
    title: "Kiosk"
    icon: mdi:tablet
    show_in_sidebar: true
    require_admin: false
  ui-mobile:
    mode: yaml
    filename: ui-mobile.yaml
    title: "Mobile"
    icon: mdi:cellphone
    show_in_sidebar: true
    require_admin: false
  ui-debug:
    mode: yaml
    filename: ui-debug.yaml
    title: "Debug"
    icon: mdi:bug-check
    show_in_sidebar: true
    require_admin: true
  ui-test:
    mode: yaml
    filename: ui-test.yaml
    title: "Test"
    icon: mdi:tools
    show_in_sidebar: true
    require_admin: true
